### ISSUE TITLE
jest-worker fails and resources won't build 

### ISSUE THREAD

**Issue by juddisjudd** [Armoury-Software/ArmouryFiveM#21]
As the title says, resources fail to build with yarn I assume because jest-worker fails.

**Comment by maziluradu** [comment]
@juddisjudd That doesn't seem to happen for me. What node version are you using? Also, can you post the full error here?

**Comment by maziluradu** [comment]
@juddisjudd The issue should now be fixed. Please pull the latest changes on the master branch and let me know if it works now.
